apiVersion: v1
kind: Service
metadata:
  name: web-only-service
spec:
  selector:
    app: web-only
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 443
    targetPort: 443
  type: LoadBalancer