name: Build and Deploy Discourse to GitHub Container Registry

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    # Sets the permissions granted to the `GITHUB_TOKEN` for the actions in this job.
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    env:
      FF_NETWORK_PER_BUILD: "true"

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y coreutils bash git grep jq

    - name: Create Docker Network
      run: docker network create discourse_network

    - name: Clone Discourse Docker repository
      run: git clone --depth=1 https://github.com/discourse/discourse_docker $GITHUB_WORKSPACE/discourse

    - name: Bootstrap Data
      run: |
        cd $GITHUB_WORKSPACE/discourse
        cp samples/data.yml containers
        ./launcher bootstrap data --docker-args "--net=discourse_network"
        ./launcher start data --docker-args "--net=discourse_network"

    - name: Bootstrap Discourse
      run: |
        cd $GITHUB_WORKSPACE/discourse
        cp samples/web_only.yml containers
        sed -i "s/smtp\.example\.com/smtp2\.example\.com/g" containers/web_only.yml
        sed -i "s/discourse\.example\.com/discourse2\.example\.com/g" containers/web_only.yml
        ./launcher bootstrap web_only --docker-args "--net=discourse_network"
        ./launcher start-cmd web_only

    - name: Generate Version from Timestamp
      id: version
      run: echo "VERSION=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

    - name: Tag Docker Image
      run: |
        docker tag local_discourse/web_only ghcr.io/${{ github.repository }}/web-only:${{ env.VERSION }}
        docker tag local_discourse/data ghcr.io/${{ github.repository }}/data:${{ env.VERSION }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Push Docker Image to GitHub Container Registry
      run: |
        docker push ghcr.io/${{ github.repository }}/web-only:${{ env.VERSION }}
        docker push ghcr.io/${{ github.repository }}/data:${{ env.VERSION }}